### ISSUE TITLE
Collection of images to add

### ISSUE THREAD

**Issue by fennectech** [xinitrc-ls/randomfox.ca#6]
I have some 12K fox pictures sitting on my harddrive from exploring the net  I know they arent links  but  The quantity is **SIGNIFICANT**
https://gyazo.com/71574bab4bf7f5eb801d67b9697187af

**Comment by xinitrc-dev** [comment]
I don't even have that much space available on my hosting service ;D
One of the reasons it's gotta be links lol

In any case, I salute you for having that many fox pictures! o7

**Comment by fennectech** [comment]
Why not stick them on github and use it to serve them?  Retroarch uses that for their boxarts

**Comment by fennectech** [comment]
https://github.com/xinitrc-dev/randomfox.ca/blob/master/images/1.jpg?raw=true

Github provides a verry determinable url that you can directly access the images from!

**Comment by fennectech** [comment]
@xinitrc-dev  Ive done a thing!  
Idk if i did it correctly but this method should work!
https://github.com/xinitrc-dev/randomfox.ca/pull/7

**Comment by xinitrc-dev** [comment]
@fennectech While hosting on GitHub would definitely solve the storage problem, it will not solve the copyright ones. I don't want to have responsibility for those, especially as it's in my plans to make user submissions quite easy.
Again, sorry about that but I don't want to move further without doing the links.
P.S.: I promise to heavily start working on this project again soon, as I have gotten quite some free time now :P

**Comment by fennectech** [comment]
Oof. Coppyright is a hard one.  :).

**Comment by fennectech** [comment]
Were using it on our discord server for a .fox command :D
