### ISSUE TITLE
Minor issue, text and image api show http

### ISSUE THREAD

**Issue by xXBuilderBXx** [xinitrc-ls/randomfox.ca#9]
Main home page text shows
`API is Available: http://randomfox.ca/floof`
This should be https also the API image url shows http even if you use https also the `Share this fox!`.

**Comment by xinitrc-dev** [comment]
Yeah, good call. All links will autoredirect to https but to avoid unnecessary redirects I've updated them. 6e5ef7f345372885df0e59c697d3f69dc1151755
